name: Hourly File Check and Creation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 * * * *"

jobs:
  check_and_create_file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: check_file
        id: check_file
        uses: andstor/file-existence-action@v2
        with:
          files: rules/MyDirect.SERVER.update.list

      - name: create_file
        if: ${{ !steps.check_file.outputs.files_exists }}
        run: |
          echo "#" > rules/MyDirect.SERVER.update.list

      - name: Add changes to the repository
        run: |
          git add .
          git status

      - name: Commit and push changes
        run: |
          git commit -m "Create file ules/MyDirect.SERVER.update.list" -a
          git push
